easy_admin:

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    entities:
        # List the entity class name you want to manage
        Entreprises:
            class: App\Entity\Company
            disabled_actions: ['new']
            list:
                title: Les Entreprises
                fields:
                    - id
                    - { property: 'company_name', label: "Nom de l'entreprise" }
                    - { property: 'contact_name', label: "Nom du contact" }
                    - { property: 'contact_phone', label: "Téléphone du contact" }
                    - { property: 'email', label: "Adresse mail" }
                    - { property: 'picture', type: 'image', label: "Image de l'entreprise" }
                    - { property: 'project', label: "Projet" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: ''}
                    - { name: 'search', label: 'Rechercher une entreprise'}
            form:
                title: Modifier une Entreprise
                fields:
                    - { property: 'company_name', label: "Nom de l'entreprise" }
                    - { property: 'contact_name', label: "Nom du contact" }
                    - { property: 'contact_phone', label: "Téléphone du contact" }
                    - { property: 'email', label: "Adresse mail" }
                    - { property: 'picture', label: "Ajouter une image" }
                    - { property: 'project', label: "Projet" }
                    - { property: 'isAdmin', label: "Admin?"}
            show:
                title: "Détails de l'entreprise"



        Talents:
            class: App\Entity\Talent
            disabled_actions: ['new']
            list:
                title: Les Talents
                fields:
                    - id
                    - { property: 'firstname', label: "Prénom" }
                    - { property: 'lastname', label: "Nom" }
                    - { property: 'email', label: "Email" }
                    - { property: 'phone', label: "Téléphone" }
                    - { property: 'skills', label: "Compétences" }
                    - { property: 'picture', type: 'image', label: "Photo" }
                    - { property: 'linkedin_profile', label: "Profil LinkedIn" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: '' }
                    - { name: 'search', label: 'Rechercher un talent'}
            form:
                title: Modifier un Talent
                fields:
                    - { property: 'firstname', label: "Prénom" }
                    - { property: 'lastname', label: "Nom" }
                    - { property: 'email', label: "Email" }
                    - { property: 'phone', label: "Téléphone" }
                    - { property: 'skills', label: "Compétences" }
                    - { property: 'picture', label: "Ajouter une photo" }
                    - { property: 'linkedin_profile', label: "Profil LinkedIn" }
                    - { property: 'isAdmin', label: "Admin?"}
            show:
                title: "Détails du talent"
                fields:
                    - { property: 'firstname', label: "Prénom" }
                    - { property: 'lastname', label: "Nom" }
                    - { property: 'email', label: "Email" }
                    - { property: 'phone', label: "Téléphone" }
                    - { property: 'skills', label: "Compétences" }
                    - { property: 'picture', label: "Ajouter une photo" }
                    - { property: 'linkedin_profile', label: "Profil LinkedIn" }
                    - { property: 'isAdmin', label: "Admin?"}
                    - { property: 'username', label: "Username"}

        Email:
            class: App\Entity\Email
            disabled_actions: ['show']
            list:
                title: Emails de contact
                fields:
                    - { property: 'address', label: "Email" }
                    - { property: 'usertype.type', label: "Type d'utilisateur" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: '' }
                    - { name: 'search', label: 'Rechercher un email'}
                    - { name: 'new', label: 'Ajouter un email'}
            form:
                title: Ajouter ou modifier un email de contact
                fields:
                    - { property: 'address', label: "Email" }
                    - { property: 'user_type', label: "Type d'utilisateur" }

        Type_utilisateurs:
            class: App\Entity\Usertype
            disabled_actions: ['show']
            list:
                title: types d'utilisateurs
                fields:
                    - id
                    - { property: 'type', label: "Type d'utilisateur" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: '' }
                    - { name: 'search', label: "Rechercher un type d'utilisateur"}
                    - { name: 'new', label: "Ajouter un type d'utilisateur"}
            form:
                title: Ajouter ou modifier un type d'utilisateur
                fields:
                    - { property: 'type', label: "Type d'utilisateur" }

        Offres_emploi:
            class: App\Entity\Opportunity
            list:
                title: Offres d'emploi
                fields:
                    - id
                    - { property: 'company.company_name', label: "Nom de l'entreprise" }
                    - { property: 'title', label: "Intitulé de l'offre" }
                    - { property: 'body', label: "Détails de l'offre" }
                    - { property: 'place', label: "Ville" }
                    - { property: 'company.contact_name', label: "Nom du contact" }
                    - { property: 'company.email', label: "Email du contact" }
                    - { property: 'salary', label: "Salaire indicatif" }
                    - { property: 'skills_required', label: "Compétences requises" }
                    - { property: 'required_expertise', label: "Expérience requise" }
                    - { property: 'remote_possibility', label: "Possibilité de télétravail" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: '' }
                    - { name: 'search', label: "Rechercher une offre d'emploi"}
                    - { name: 'new', label: "Ajouter une offre d'emploi"}
            form:
                title: Ajouter ou modifier une offre d'emploi
                fields:
                    - { property: 'company', label: "Entreprise" }
                    - { property: 'title', label: "Intitulé de l'offre" }
                    - { property: 'body', label: "Détails de l'offre" }
                    - { property: 'place', label: "Ville" }
                    - { property: 'salary', label: "Salaire indicatif" }
                    - { property: 'skills_required', label: "Compétences requises" }
                    - { property: 'required_expertise', label: "Expérience requise" }
                    - { property: 'remote_possibility', label: "Possibilité de télétravail" }
            show:
                title: "Détails de l'offre"

        Competences:
            class: App\Entity\Skill
            list:
                title: Les compétences
                fields:
                    - id
                    - { property: 'name', label: "Compétence" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: '' }
                    - { name: 'search', label: 'Rechercher une compétence'}
                    - { name: 'new', label: 'Ajouter une compétence'}
            form:
                title: Ajouter ou modifier une compétence
                fields:
                    - { property: 'name', label: "Compétence" }

        Evènements:
            class: App\Entity\Event
            list:
                title: Les évènements
                fields:
                    - id
                    - { property: 'title', label: "Intitulé de l'évènement" }
                    - { property: 'description', label: "Détails de l'évènement" }
                    - { property: 'picture', label: "Image d'illustration" }
                    - { property: 'begins', label: "Date de début de l'évènement" }
                    - { property: 'ends', label: "Date de fin de l'évènement" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: '' }
                    - { name: 'search', label: 'Rechercher un évènement'}
                    - { name: 'new', label: 'Ajouter un évènement'}
            form:
                title: Ajouter ou modifier évènement
                fields:
                    - { property: 'title', label: "Intitulé de l'évènement" }
                    - { property: 'description', label: "Détails de l'évènement" }
                    - { property: 'picture', type: 'file', label: "Ajouter une image" }
                    - { property: 'begins', label: "Date de début de l'évènement" }
                    - { property: 'ends', label: "Date de fin de l'évènement" }

        Articles:
            class: App\Entity\Post
            list:
                title: Messages du blog
                fields:
                    - id
                    - { property: 'title', label: "Titre de l'article" }
                    - { property: 'body', label: "Corps de l'article" }
                    - { property: 'picture', label: "Image" }
                    - { property: 'published', label: "Date de publication" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: '' }
                    - { name: 'search', label: 'Rechercher un article'}
                    - { name: 'new', label: 'Ajouter un article'}
            form:
                title: Ajouter ou modifier un article
                fields:
                    - { property: 'title', label: "Titre de l'article" }
                    - { property: 'body', label: "Corps de l'article" }
                    - { property: 'picture', type: 'file', label: "Ajouter une image" }

        Produits:
            class: App\Entity\Product
            list:
                title: Produits
                fields:
                    - id
                    - { property: 'name', label: "Intitulé du produit" }
                    - { property: 'description', label: "Description du produit" }
                    - { property: 'price', label: "Prix en €" }
                    - { property: 'picture', label: "Image d'illustration" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: '' }
                    - { name: 'search', label: 'Rechercher un produit'}
                    - { name: 'new', label: 'Ajouter un produit'}
            form:
                title: Ajouter ou modifier un produit
                fields:
                    - { property: 'name', label: "Intitulé du produit" }
                    - { property: 'description', label: "Description du produit" }
                    - { property: 'price', label: "Prix en €" }
                    - { property: 'picture', type: 'file', label: "Ajouter une image" }


    site_name: 'Corse Connexion'

    design:
        brand_color: 'Orange'
        form_theme: 'vertical'
