easy_admin:

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    entities:
        # List the entity class name you want to manage
        Company:
            class: App\Entity\Company
            list:
                title: Les Entreprises
                fields:
                    - id
                    - { property: 'company_name', label: "Nom de l'entreprise" }
                    - { property: 'contact_name', label: "Nom du contact" }
                    - { property: 'contact_phone', label: "Téléphone du contact" }
                    - { property: 'email', label: "Adresse mail" }
                    - { property: 'picture', label: "Image de l'entreprise" }
                    - { property: 'project', label: "Projet" }
                actions:
                    - { name: 'show', icon: 'info-circle', label: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'delete', icon: 'trash', label: ''}
                    - { name: 'search', label: 'Rechercher une entreprise'}
                    - { name: 'new', label: 'Ajouter une entreprise'}
            form:
                title: Ajouter un Talent
                fields:
                    - { property: 'company_name', label: "Nom de l'entreprise" }
                    - { property: 'contact_name', label: "Nom du contact" }
                    - { property: 'contact_phone', label: "Téléphone du contact" }
                    - { property: 'email', label: "Adresse mail" }
                    - { property: 'picture', label: "Image de l'entreprise" }
                    - { property: 'project', label: "Projet" }



        Talent:
            class: App\Entity\Talent
            list:
                title: Les Talents
                fields:
                    - id
                    - { property: 'firstname', label: "Prénom" }
                    - { property: 'lastname', label: "Nom" }
                    - { property: 'email', label: "Email" }
                    - { property: 'phone', label: "Téléphone" }
                    - { property: 'skills', label: "Compétences" }
                    - { property: 'picture', label: "Photo" }
                    - { property: 'linkedin_profile', label: "Profil LinkedIn" }
                actions:
                - { name: 'show', icon: 'info-circle', label: 'Show' }
                - { name: 'edit', icon: 'pencil', label: 'Edit' }
                - { name: 'delete', icon: 'trash', label: '' }
                - { name: 'search', label: 'Rechercher un talent'}
                - { name: 'new', label: 'Ajouter un talent'}
            form:
                title: Ajouter un Talent
                fields:
                    - { property: 'firstname', label: "Prénom" }
                    - { property: 'lastname', label: "Nom" }
                    - { property: 'email', label: "Email" }
                    - { property: 'phone', label: "Téléphone" }
                    - { property: 'skills', label: "Compétences" }
                    - { property: 'picture', label: "Photo" }
                    - { property: 'linkedin_profile', label: "Profil LinkedIn" }

        Email:
            class: App\Entity\Email
            list:
                title: Emails de contact
                fields:
                    - { property: 'address', label: "Email" }
                    - { property: 'usertype.type', label: "Type d'utilisateur" }
                actions:
                - { name: 'show', icon: 'info-circle', label: 'Show' }
                - { name: 'edit', icon: 'pencil', label: 'Edit' }
                - { name: 'delete', icon: 'trash', label: '' }
                - { name: 'search', label: 'Rechercher un email'}
                - { name: 'new', label: 'Ajouter un email'}
            form:
                title: Ajouter un email de contact
                fields:
                    - { property: 'address', label: "Email" }
                    - { property: 'usertype.type', label: "Type d'utilisateur" }

        usertype:
            class: App\Entity\Usertype
            list:
                title: types d'utilisateurs
                fields:
                    - id
                    - { property: 'type', label: "Type d'utilisateur" }
                actions:
                - { name: 'show', icon: 'info-circle', label: 'Show' }
                - { name: 'edit', icon: 'pencil', label: 'Edit' }
                - { name: 'delete', icon: 'trash', label: '' }
                - { name: 'search', label: "Rechercher un type d'utilisateur"}
                - { name: 'new', label: "Ajouter un type d'utilisateur"}
            form:
                title: ajouter un type d'utilisateur
                fields:
                    - { property: 'type', label: "Type d'utilisateur" }

        Opportunity:
            class: App\Entity\Opportunity
            list:
                title: Offres d'emploi
                fields:
                    - id
                    - { property: 'company.company_name', label: "Nom de l'entreprise" }
                    - { property: 'title', label: "Intitulé de l'offre" }
                    - { property: 'body', label: "Détails de l'offre" }
                    - { property: 'place', label: "Ville" }
                    - { property: 'company.contact_name', label: "Nom du contact" }
                    - { property: 'company.email', label: "Email du contact" }
                    - { property: 'salary', label: "Salaire indicatif" }
                    - { property: 'skills_required', label: "Compétences requises" }
                    - { property: 'required_expertise', label: "Expérience requise" }
                    - { property: 'remote_possibility', label: "Possibilité de télétravail" }
                actions:
                - { name: 'show', icon: 'info-circle', label: 'Show' }
                - { name: 'edit', icon: 'pencil', label: 'Edit' }
                - { name: 'delete', icon: 'trash', label: '' }
                - { name: 'search', label: "Rechercher une offre d'emploi"}
                - { name: 'new', label: "Ajouter une offre d'emploi"}
            form:
                title: Ajouter une offre d'emploi
                fields:
                    - { property: 'company', label: "Entreprise" }
                    - { property: 'title', label: "Intitulé de l'offre" }
                    - { property: 'body', label: "Détails de l'offre" }
                    - { property: 'place', label: "Ville" }
                    - { property: 'salary', label: "Salaire indicatif" }
                    - { property: 'skills_required', label: "Compétences requises" }
                    - { property: 'required_expertise', label: "Expérience requise" }
                    - { property: 'remote_possibility', label: "Possibilité de télétravail" }

        Skill:
            class: App\Entity\Skill
            list:
                title: Les compétences
                fields:
                    - id
                    - { property: 'name', label: "Compétence" }
                actions:
                - { name: 'show', icon: 'info-circle', label: 'Show' }
                - { name: 'edit', icon: 'pencil', label: 'Edit' }
                - { name: 'delete', icon: 'trash', label: '' }
                - { name: 'search', label: 'Rechercher une compétence'}
                - { name: 'new', label: 'Ajouter une compétence'}
            form:
                title: Ajouter une nouvelle compétence
                fields:
                    - { property: 'name', label: "Compétence" }

        Event:
            class: App\Entity\Event
            list:
                title: Les évènements
                fields:
                    - id
                    - { property: 'title', label: "Intitulé de l'évènement" }
                    - { property: 'description', label: "Détails de l'évènement" }
                    - { property: 'picture', label: "Image d'illustration" }
                    - { property: 'begins', label: "Date de début de l'évènement" }
                    - { property: 'ends', label: "Date de fin de l'évènement" }
                actions:
                - { name: 'show', icon: 'info-circle', label: 'Show' }
                - { name: 'edit', icon: 'pencil', label: 'Edit' }
                - { name: 'delete', icon: 'trash', label: '' }
                - { name: 'search', label: 'Rechercher un évènement'}
                - { name: 'new', label: 'Ajouter un évènement'}
            form:
                title: Ajouter un nouvel évènement
                fields:
                    - { property: 'title', label: "Intitulé de l'évènement" }
                    - { property: 'description', label: "Détails de l'évènement" }
                    - { property: 'picture', label: "Image d'illustration" }
                    - { property: 'begins', label: "Date de début de l'évènement" }
                    - { property: 'ends', label: "Date de fin de l'évènement" }

        Post:
            class: App\Entity\Post
            list:
                title: Messages du blog
                fields:
                    - id
                    - { property: 'title', label: "Titre de l'article" }
                    - { property: 'body', label: "Corps de l'article" }
                    - { property: 'picture', label: "Image" }
                    - { property: 'published', label: "Date de publication" }
                actions:
                - { name: 'show', icon: 'info-circle', label: 'Show' }
                - { name: 'edit', icon: 'pencil', label: 'Edit' }
                - { name: 'delete', icon: 'trash', label: '' }
                - { name: 'search', label: 'Rechercher un article'}
                - { name: 'new', label: 'Ajouter un article'}
            form:
                title: Ajouter un post au Blog
                fields:
                    - { property: 'title', label: "Titre de l'article" }
                    - { property: 'body', label: "Corps de l'article" }
                    - { property: 'picture', label: "Image" }

        Product:
            class: App\Entity\Product
            list:
                title: Produits
                fields:
                    - id
                    - { property: 'name', label: "Intitulé du produit" }
                    - { property: 'description', label: "Description du produit" }
                    - { property: 'price', label: "Prix en €" }
                    - { property: 'picture', label: "Image d'illustration" }
                actions:
                - { name: 'show', icon: 'info-circle', label: 'Show' }
                - { name: 'edit', icon: 'pencil', label: 'Edit' }
                - { name: 'delete', icon: 'trash', label: '' }
                - { name: 'search', label: 'Rechercher un produit'}
                - { name: 'new', label: 'Ajouter un produit'}
            form:
                title: Ajouter un Produit
                fields:
                    - { property: 'name', label: "Intitulé du produit" }
                    - { property: 'description', label: "Description du produit" }
                    - { property: 'price', label: "Prix en €" }
                    - { property: 'picture', label: "Image d'illustration" }


    site_name: 'Corse Connexion'

    design:
        brand_color: 'Orange'
