security:
    encoders:
        App\Entity\Talent: plaintext
#            algorithm: bcrypt
#        App\Entity\Company:
#            algorithm: bcrypt
    providers:
        talent_provider:
            entity:
                class: App\Entity\Talent
                property: email
        company_provider:
            entity:
                class: App\Entity\Company
                property: username
        chain_provider:
            chain:
                providers: [talent_provider, company_provider]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            json_login:
                check_path: /login
                provider: chain_provider
                username_path: email
            guard:
                authenticators:
                - App\Security\TokenAuthenticator
                provider: chain_provider
            logout:
                path:   /logout
                target: /


    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }