vich_uploader:
    db_driver: orm
    mappings:
        pictures:
            uri_prefix: /pictures/
            upload_destination: '%kernel.root_dir%/../public/pictures/'
            namer: vich_uploader.namer_uniqid

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
