#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api:
    path: /api
    controller: App\SecurityController::api

login_check:
    path:     /api/login_check
    methods:  [POST]